GET http://localhost:5500/n1wqq9
###
POST http://localhost:5500/
content-type: application/json

{
    "url": "https://www.google.com"
}

###
POST http://localhost:5500/
content-type: application/json

{
    "url": "https://www.google.com",
    "code":"google"
}

###
GET http://localhost:5500/google